✨ Add new Kubernetes resources for analytics and imgproxy services, and improve database readiness checks in existing deployments

diff --git a/k8s/supabase/base/db.yaml b/k8s/supabase/base/db.yaml
--- a/k8s/supabase/base/db.yaml
+++ b/k8s/supabase/base/db.yaml
@@ -14,33 +14,33 @@ spec:
       labels:
         app: db
     spec:
-      # initContainers:
-      # - name: init-db-scripts
-      #   image: supabase/postgres
-      #   command: ["/bin/sh", "-c"]
-      #   args:
-      #     - |
-      #       echo "Copying init scripts into existing image script directory..."
-      #       cp -r /docker-entrypoint-initdb.d/* /initdb.d/
-      #       cp /custom-init-scripts/98-webhooks.sql /initdb.d/init-scripts/
-      #       cp /custom-init-scripts/99-roles.sql /initdb.d/init-scripts/
-      #       cp /custom-init-scripts/99-jwt.sql /initdb.d/init-scripts/
+      initContainers:
+      - name: init-db-scripts
+        image: supabase/postgres
+        command: ["/bin/sh", "-c"]
+        args:
+          - |
+            echo "Copying init scripts into existing image script directory..."
+            cp -r /docker-entrypoint-initdb.d/* /initdb.d/
+            cp /custom-init-scripts/98-webhooks.sql /initdb.d/init-scripts/
+            cp /custom-init-scripts/99-roles.sql /initdb.d/init-scripts/
+            cp /custom-init-scripts/99-jwt.sql /initdb.d/init-scripts/
             
-      #       cp /custom-init-scripts/97-_supabase.sql /initdb.d/migrations/
-      #       cp /custom-init-scripts/99-logs.sql /initdb.d/migrations/
-      #       cp /custom-init-scripts/99-pooler.sql /initdb.d/migrations/
-      #       cp /custom-init-scripts/99-realtime.sql /initdb.d/migrations/
+            cp /custom-init-scripts/97-_supabase.sql /initdb.d/migrations/
+            cp /custom-init-scripts/99-logs.sql /initdb.d/migrations/
+            cp /custom-init-scripts/99-pooler.sql /initdb.d/migrations/
+            cp /custom-init-scripts/99-realtime.sql /initdb.d/migrations/
 
-      #       echo "Copying user-defined migration scripts..."
-      #       cp /custom-migrations/* /initdb.d/migrations/ || echo "Skip migrations"
-      #       echo "Initialization scripts are ready"
-      #   volumeMounts:
-      #       - mountPath: /custom-init-scripts
-      #         name: custom-init-scripts
-      #       - mountPath: /custom-migrations
-      #         name: custom-migrations
-      #       - mountPath: /initdb.d
-      #         name: initdb-scripts-data
+            #echo "Copying user-defined migration scripts..."
+            #cp /custom-migrations/* /initdb.d/migrations/ || echo "Skip migrations"
+            echo "Initialization scripts are ready"
+        volumeMounts:
+            - mountPath: /custom-init-scripts
+              name: custom-init-scripts
+            - mountPath: /custom-migrations
+              name: custom-migrations
+            - mountPath: /initdb.d
+              name: initdb-scripts-data
       containers:
       - name: db
         image: supabase/postgres
@@ -55,20 +55,20 @@ spec:
           limits:
             memory: "1Gi"
             cpu: "500m"
-        readinessProbe:
-          exec:
-            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
-          initialDelaySeconds: 5
-          periodSeconds: 5
-          timeoutSeconds: 5
-          failureThreshold: 10
-        livenessProbe:
-          exec:
-            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
-          initialDelaySeconds: 30
-          periodSeconds: 5
-          timeoutSeconds: 5
-          failureThreshold: 10
+        # readinessProbe:
+        #   exec:
+        #     command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
+        #   initialDelaySeconds: 5
+        #   periodSeconds: 5
+        #   timeoutSeconds: 5
+        #   failureThreshold: 10
+        # livenessProbe:
+        #   exec:
+        #     command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
+        #   initialDelaySeconds: 30
+        #   periodSeconds: 5
+        #   timeoutSeconds: 5
+        #   failureThreshold: 10
         env:
         - name: POSTGRES_HOST
           value: /var/run/postgresql
@@ -94,20 +94,20 @@ spec:
         volumeMounts:
         - name: postgres-data
           mountPath: /var/lib/postgresql/data
-        # - name: initdb-scripts-data
-        #   mountPath: /docker-entrypoint-initdb.d
+        - name: initdb-scripts-data
+          mountPath: /docker-entrypoint-initdb.d
       volumes:
       - name: postgres-data
         persistentVolumeClaim:
           claimName: db-pvc
-      # - name: initdb-scripts-data
-      #   emptyDir: {}
-      # - name: custom-init-scripts
-      #   configMap:
-      #     name: postgres-init-scripts
-      # - name: custom-migrations
-      #   configMap:
-      #     name: postgres-migration-scripts
+      - name: initdb-scripts-data
+        emptyDir: {}
+      - name: custom-init-scripts
+        configMap:
+          name: postgres-init-scripts
+      - name: custom-migrations
+        configMap:
+          name: postgres-migration-scripts
 ---
 apiVersion: v1
 kind: Service
@@ -119,7 +119,6 @@ spec:
   ports:
   - port: 5432
     targetPort: 5432
-    name: db
   type: ClusterIP
 ---
 apiVersion: v1
@@ -133,59 +132,59 @@ spec:
     requests:
       storage: 1Gi
 ---
-apiVersion: batch/v1
-kind: Job
-metadata:
-  name: supabase-migration
-spec:
-  ttlSecondsAfterFinished: 100
-  template:
-    spec:
-      containers:
-        - name: migration
-          image: postgres:13-alpine
-          env:
-          - name: PGPASSWORD
-            value: $(POSTGRES_PASSWORD)
-          envFrom:
-          - configMapRef:
-              name: supabase-common-config
-          - secretRef:
-              name: supabase-common-secrets
-          command: ["/bin/sh", "-c"]
-          args:
-            - |
-              echo "Waiting for PostgreSQL to be ready..."
-              until pg_isready -h $(POSTGRES_HOST).supabase -p $(POSTGRES_PORT) -U postgres; do
-                echo "PostgreSQL is unavailable - sleeping 5s"
-                sleep 5
-              done
+# apiVersion: batch/v1
+# kind: Job
+# metadata:
+#   name: supabase-migration
+# spec:
+#   ttlSecondsAfterFinished: 100
+#   template:
+#     spec:
+#       containers:
+#         - name: migration
+#           image: postgres:13-alpine
+#           env:
+#           - name: PGPASSWORD
+#             value: $(POSTGRES_PASSWORD)
+#           envFrom:
+#           - configMapRef:
+#               name: supabase-common-config
+#           - secretRef:
+#               name: supabase-common-secrets
+#           command: ["/bin/sh", "-c"]
+#           args:
+#             - |
+#               echo "Waiting for PostgreSQL to be ready..."
+#               until pg_isready -h $(POSTGRES_HOST).supabase -p $(POSTGRES_PORT) -U postgres; do
+#                 echo "PostgreSQL is unavailable - sleeping 5s"
+#                 sleep 5
+#               done
               
-              echo "PostgreSQL is up - executing migration scripts"
-              for script in /init-scripts/*.sql; do
-                echo "Executing $script"
-                psql -h $(POSTGRES_HOST) -p $(POSTGRES_PORT) -U supabase_admin -d $(POSTGRES_DB) -f "$script"
-              done
+#               echo "PostgreSQL is up - executing migration scripts"
+#               for script in /init-scripts/*.sql; do
+#                 echo "Executing $script"
+#                 psql -h $(POSTGRES_HOST) -p $(POSTGRES_PORT) -U supabase_admin -d $(POSTGRES_DB) -f "$script"
+#               done
 
-              #psql -h $(POSTGRES_HOST) -p $(POSTGRES_PORT) -U supabase_admin -d $(POSTGRES_DB) -f /migrations/20250526235959_mon_leo_schema.sql
-              # Ajoute d'autres scripts si besoin
-          resources:
-            requests:
-              memory: "128Mi"
-              cpu: "100m"
-            limits:
-              memory: "256Mi"
-              cpu: "200m"
-          volumeMounts:
-          - name: init-scripts
-            mountPath: /init-scripts
-          - name: migrations
-            mountPath: /migrations
-      restartPolicy: OnFailure
-      volumes:
-      - name: init-scripts
-        configMap:
-          name: postgres-init-scripts
-      - name: migrations
-        configMap:
-          name: postgres-migration-scripts
+#               #psql -h $(POSTGRES_HOST) -p $(POSTGRES_PORT) -U supabase_admin -d $(POSTGRES_DB) -f /migrations/20250526235959_mon_leo_schema.sql
+#               # Ajoute d'autres scripts si besoin
+#           resources:
+#             requests:
+#               memory: "128Mi"
+#               cpu: "100m"
+#             limits:
+#               memory: "256Mi"
+#               cpu: "200m"
+#           volumeMounts:
+#           - name: init-scripts
+#             mountPath: /init-scripts
+#           - name: migrations
+#             mountPath: /migrations
+#       restartPolicy: OnFailure
+#       volumes:
+#       - name: init-scripts
+#         configMap:
+#           name: postgres-init-scripts
+#       - name: migrations
+#         configMap:
+#           name: postgres-migration-scripts
